/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Product {

  /**
   * Product category for bar organization
   */
  category: 'DRINKS' | 'BEER_WINE_NONALC' | 'SHOTS';
  id: number;

  /**
   * List of ingredient IDs for this product
   */
  ingredientIds?: Array<number>;
  name: string;
  price: number;

  /**
   * Whether this product requires a deposit token (Pfand)
   */
  requiresDeposit?: boolean;
}
