/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Product {

  /**
   * Product category for bar organization
   */
  category: 'DRINKS' | 'BEER_WINE_NONALC' | 'SHOTS';
  id: number;
  name: string;
  price: number;
}
