/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductSalesEntry {
  category?: 'DRINKS' | 'BEER_WINE_NONALC' | 'SHOTS';
  productId?: number;
  productName?: string;

  /**
   * Rank by sales volume (1 = highest)
   */
  rank?: number;

  /**
   * Total units sold across all matched orders
   */
  totalQuantitySold?: number;

  /**
   * Total revenue from this product: price × totalQuantitySold
   */
  totalRevenue?: number;
}
