/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {OrderedItem} from '../models/ordered-item';

export interface PurchaseOrder {
  id?: number;
  items?: Array<OrderedItem>;
  orderedAt?: string;
  returnedCupsCount?: number;

  /**
   * Optional tip amount in EUR
   */
  tipAmount?: number;

  /**
   * Number of new deposit tokens issued with this order
   */
  tokensIssued?: number;
}
