/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {OrderedItem} from '../models/ordered-item';

export interface PurchaseOrder {
  id?: number;
  items?: Array<OrderedItem>;
  orderedAt?: string;

  /**
   * Number of cups returned with this order
   */
  returnedCupsCount?: number;
}
