/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext} from '@angular/common/http';
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';

import {BaseService} from '../base-service';
import {ApiConfiguration} from '../api-configuration';
import {StrictHttpResponse} from '../strict-http-response';

import {getIngredients, GetIngredients$Params} from '../fn/ingredient-controller/get-ingredients';
import {Ingredient} from '../models/ingredient';

@Injectable({ providedIn: 'root' })
export class IngredientControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getIngredients()` */
  static readonly GetIngredientsPath = '/api/ingredients';

  /**
   * Get all ingredients.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getIngredients()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIngredients$Response(params?: GetIngredients$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Ingredient>>> {
    return getIngredients(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all ingredients.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getIngredients$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIngredients(params?: GetIngredients$Params, context?: HttpContext): Observable<Array<Ingredient>> {
    return this.getIngredients$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Ingredient>>): Array<Ingredient> => r.body)
    );
  }

}
