/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext} from '@angular/common/http';
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';

import {BaseService} from '../base-service';
import {ApiConfiguration} from '../api-configuration';
import {StrictHttpResponse} from '../strict-http-response';

import {createOrder, CreateOrder$Params} from '../fn/purchase-order-controller/create-order';
import {getOrderById, GetOrderById$Params} from '../fn/purchase-order-controller/get-order-by-id';
import {getOrders, GetOrders$Params} from '../fn/purchase-order-controller/get-orders';
import {PurchaseOrder} from '../models/purchase-order';

@Injectable({ providedIn: 'root' })
export class PurchaseOrderControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getOrders()` */
  static readonly GetOrdersPath = '/api/orders';

  /**
   * Get all orders.
   *
   * This endpoint gets all currently saved orders
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrders$Response(params?: GetOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PurchaseOrder>>> {
    return getOrders(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all orders.
   *
   * This endpoint gets all currently saved orders
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrders(params?: GetOrders$Params, context?: HttpContext): Observable<Array<PurchaseOrder>> {
    return this.getOrders$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PurchaseOrder>>): Array<PurchaseOrder> => r.body)
    );
  }

  /** Path part for operation `createOrder()` */
  static readonly CreateOrderPath = '/api/orders';

  /**
   * Create new Order.
   *
   * This endpoint creates a new purchase order
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder$Response(params: CreateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<PurchaseOrder>> {
    return createOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new Order.
   *
   * This endpoint creates a new purchase order
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder(params: CreateOrder$Params, context?: HttpContext): Observable<PurchaseOrder> {
    return this.createOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<PurchaseOrder>): PurchaseOrder => r.body)
    );
  }

  /** Path part for operation `getOrderById()` */
  static readonly GetOrderByIdPath = '/api/orders/{id}';

  /**
   * Get Order by id.
   *
   * This endpoint gets all orders by provided id
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrderById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderById$Response(params: GetOrderById$Params, context?: HttpContext): Observable<StrictHttpResponse<PurchaseOrder>> {
    return getOrderById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Order by id.
   *
   * This endpoint gets all orders by provided id
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrderById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderById(params: GetOrderById$Params, context?: HttpContext): Observable<PurchaseOrder> {
    return this.getOrderById$Response(params, context).pipe(
      map((r: StrictHttpResponse<PurchaseOrder>): PurchaseOrder => r.body)
    );
  }

}
